'use client';
import CaseEditor from './case-editor';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import {CARD_FILES} from '../public/tools/tarot/vendor/tarot-lite/assets.js';
import {BookOpen,History,Trash2,ArrowUpRight,Clock3,Download,Upload,ShieldAlert} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Switch} from '@/components/ui/switch';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Alert,AlertDescription,AlertTitle} from '@/components/ui/alert';

import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {listRecords,deleteRecord,clearRecords,getPreferences,setPreferences,createCaseArchive,previewCaseImport,importCaseArchive,createTarotArchive,previewTarotImport,importTarotArchive,type SavedRecord,type Preferences,type CaseImportPreview} from '../public/shared/storage.js';
import {tools,nameOf,type ToolId} from './tool-catalog';
type TarotCard={id:number;name:string;reversed?:boolean;position?:string};
const formatDate=(n:number)=>new Date(n).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
const birthSummary=(record:SavedRecord)=>{const input=record.snapshot?.profile?.input,year=record.birth?.solarDay?.year??record.birth?.lunarDay?.year??input?.year,month=record.birth?.solarDay?.month??record.birth?.lunarDay?.month??input?.month,day=record.birth?.solarDay?.day??record.birth?.lunarDay?.day??input?.day,date=year!=null&&month!=null&&day!=null?`${year} 年 ${month} 月 ${day} 日`:'出生日期未完整填写',place=record.birth?.city||record.snapshot?.profile?.location?.name||'未填写地点';return `${date} · ${place}`};
export default function PersonalPanel({kind,onClose,onOpen,revision}:{kind:string;onClose:()=>void;onOpen:(id:ToolId,record?:string)=>void;revision:number}){
 const [adding,setAdding]=useState(false);
 const [records,setRecords]=useState<SavedRecord[]>([]),[error,setError]=useState(''),[detail,setDetail]=useState<SavedRecord|null>(null),[confirm,setConfirm]=useState<string|null>(null),[prefs,setPrefs]=useState<Preferences>({featured:'auto',motion:true,locale:'zh-CN'});
 const [notice,setNotice]=useState('');
 const [pendingImport,setPendingImport]=useState<{name:string;text:string;preview:CaseImportPreview}|null>(null);
 const fileInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;try{setRecords(listRecords(kind==='history'?'tarot':'cases'));setPrefs(getPreferences());setError('')}catch(e){setError('无法读取本机数据：'+(e as Error).message)}});return()=>{active=false}},[kind,revision]);
 const update=(patch:Partial<Preferences>)=>{try{const p=setPreferences(patch);setPrefs(p);document.documentElement.dataset.motion=p.motion?'on':'off';setError('')}catch{setError('浏览器未能保存设置，请检查存储权限或剩余空间。')}};
 const exportRecords=()=>{try{const history=kind==='history',archive=history?createTarotArchive():createCaseArchive();if(!archive.records.length){setError(history?'抽牌历史还是空的，没有可导出的记录。':'命例簿还是空的，没有可导出的记录。');return}const text=JSON.stringify(archive,null,2),blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=history?`opendestiny-tarot-history-${new Date().toISOString().slice(0,10)}.json`:`redsc1-cases-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(`已导出 ${archive.records.length} 条${history?'抽牌记录':'命例'}。`);setError('')}catch(e){setError('导出失败：'+(e as Error).message)}};
 const readImport=async(file?:File)=>{if(!file)return;if(file.size>10*1024*1024){setError('文件超过 10 MB，请拆分后再导入。');return}try{const text=await file.text(),preview=kind==='history'?previewTarotImport(text):previewCaseImport(text);setPendingImport({name:file.name,text,preview});setError('');setNotice('')}catch(e){setError('导入失败：'+(e as Error).message)}};
 const applyImport=()=>{if(!pendingImport)return;try{const history=kind==='history',result=history?importTarotArchive(pendingImport.text):importCaseArchive(pendingImport.text);setRecords(listRecords(history?'tarot':'cases'));setPendingImport(null);setNotice(`已写入 ${result.added} 条${history?'抽牌记录':'命例'}${result.duplicateCount?`，跳过 ${result.duplicateCount} 条完全相同的记录`:''}。`);setError('')}catch(e){setError('导入失败：'+(e as Error).message)}};
 if(kind==='settings')return <Dialog open onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="personal-dialog settings-dialog"><DialogTitle>偏好设置</DialogTitle><DialogDescription>让这个空间适合你的节奏。</DialogDescription><div className="setting-block"><label id="language-label" htmlFor="language-select">界面语言</label><Select value={prefs.locale} onValueChange={v=>{if(v)update({locale:v as Preferences['locale']})}}><SelectTrigger id="language-select" aria-labelledby="language-label"><SelectValue>{prefs.locale==='zh-TW'?'繁體中文':'简体中文'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="zh-CN">简体中文</SelectItem><SelectItem value="zh-TW">繁體中文</SelectItem></SelectContent></Select></div><div className="setting-block"><label id="featured-label" htmlFor="featured-select">首页主工具</label><Select value={prefs.featured} onValueChange={v=>{if(v)update({featured:v as Preferences['featured']})}}><SelectTrigger id="featured-select" aria-labelledby="featured-label"><SelectValue>{prefs.featured==='auto'?'自动 · 最近 30 天最常用':nameOf(prefs.featured)}</SelectValue></SelectTrigger><SelectContent><SelectItem value="auto">自动 · 最近 30 天最常用</SelectItem>{tools.map(t=><SelectItem key={t.id} value={t.id}>固定 · {t.name}</SelectItem>)}</SelectContent></Select><p>按工具打开次数推荐；使用次数相同时保持固定顺序，没有记录时显示塔罗。也可以固定一个工具。</p></div><div className="setting-row"><label htmlFor="motion">界面动效<small>牌面悬停与轻微过渡</small></label><Switch id="motion" checked={prefs.motion} onCheckedChange={v=>update({motion:v})}/></div><div className="storage-note"><BookOpen size={17}/><p>记录仅保存在当前浏览器，不上传。换设备、使用无痕窗口或清除网站数据后，这些记录不会自动恢复。</p></div>{error&&<p role="alert" className="error-text">{error}</p>}</DialogContent></Dialog>;
 const shown=records;
 const remove=()=>{try{if(confirm==='all')clearRecords(kind==='history'?'tarot':'cases');else if(confirm)deleteRecord(confirm);setRecords(listRecords(kind==='history'?'tarot':'cases'));setConfirm(null);setError('')}catch(e){setError('删除失败：'+(e as Error).message)}};
 return <section className="records-page"><div className="records-heading"><div><p className="eyebrow">YOUR PERSONAL COLLECTION</p><h1>{kind==='history'?'抽牌历史':'命例簿'}<span>{records.length.toString().padStart(2,'0')}</span></h1><p>{kind==='history'?'留住当时的问题，也留住牌给你的视角。':'保存一份出生资料，用于八字、紫微与后续的星盘。'}</p></div><button className="quiet-danger" disabled={!shown.length} onClick={()=>setConfirm('all')}><Trash2 size={16}/>{kind==='history'?'清空历史':'清空命例'}</button></div>
 <div className="records-toolbar"><span>{kind==='cases'?'一份出生资料，通用于所有排盘工具':'按时间倒序'}</span><div className="record-create"><input ref={fileInput} className="case-file-input" type="file" accept=".json,application/json" onChange={event=>{const file=event.currentTarget.files?.[0];event.currentTarget.value='';void readImport(file)}}/><button onClick={()=>fileInput.current?.click()}><Upload size={15}/>导入</button><button disabled={!shown.length} onClick={exportRecords}><Download size={15}/>导出全部</button>{kind==='history'?<button className="record-add" onClick={()=>onOpen('tarot')}>开始新一轮 <ArrowUpRight size={16}/></button>:<button className="record-add" onClick={()=>setAdding(true)}>＋ 添加命例</button>}</div></div>
 <Alert role="note" className="browser-storage-alert"><ShieldAlert/><AlertTitle>{kind==='history'?'抽牌历史保存在当前浏览器':'命例保存在当前浏览器'}</AlertTitle><AlertDescription>{kind==='history'?'不同浏览器和设备之间不会互通；清除网站数据后将无法恢复。建议将重要抽牌记录定期导出备份。':'不同浏览器和设备之间不会互通；清除网站数据后将无法恢复。建议将重要命例定期导出备份。'}</AlertDescription></Alert>
 {notice&&<output className="success-text">{notice}</output>}{error&&<p role="alert" className="error-text">{error}</p>}{!shown.length&&!error?<Empty className="records-empty"><EmptyHeader>{kind==='history'?<History size={36} strokeWidth={1}/>:<BookOpen size={36} strokeWidth={1}/>}<EmptyTitle>这里还没有{kind==='history'?'抽牌记录':'命例'}</EmptyTitle><EmptyDescription>{kind==='history'?'完成一次抽牌后，记录会自动出现在这里。':'添加一份出生资料后，就能用于八字、紫微和后续的星盘。'}</EmptyDescription></EmptyHeader></Empty>:<div className="records-grid">{shown.map(r=><article className={'saved-card saved-'+r.kind} key={r.id}><div className="saved-meta"><span>{r.kind==='tarot'?'塔罗记录':'出生资料'}</span><button data-no-i18n aria-label={(prefs.locale==='zh-TW'?'刪除 ':'删除 ')+r.title} onClick={()=>setConfirm(r.id)}><Trash2 size={15}/></button></div><button className="saved-open" onClick={()=>setDetail(r)}><h2 data-no-i18n>{r.title}</h2>{r.kind==='tarot'?<><div className="history-preview">{r.snapshot.cards.map((c:TarotCard)=><span className="history-preview-card" key={c.id}><Image unoptimized loading="lazy" width={70} height={120} src={`/tools/tarot/assets/tarot/web/table/${CARD_FILES[c.id]}`} className={c.reversed?'reversed':''} alt={`${c.name} · ${c.reversed?'逆位':'正位'}`}/></span>)}</div><p className="history-summary"><span>{r.snapshot.spread?.name}</span><span>{r.snapshot.cards.length} 张牌</span></p></>:<p>{birthSummary(r)}</p>}<time><Clock3 size={13}/>{formatDate(r.updatedAt||r.createdAt)}</time></button>{r.kind==='tarot'?<button className="saved-action" onClick={()=>setDetail(r)}>回看这次抽牌<ArrowUpRight size={16}/></button>:<div className="case-chart-links"><button onClick={()=>onOpen('bazi',r.id)}>排八字<ArrowUpRight size={14}/></button><button onClick={()=>onOpen('ziwei',r.id)}>排紫微<ArrowUpRight size={14}/></button></div>}</article>)}</div>}
 {kind==='history'&&<p className="records-local">抽牌历史保存在当前浏览器，与命例簿分开保存。</p>}
 <Dialog open={Boolean(pendingImport)} onOpenChange={open=>{if(!open)setPendingImport(null)}}><DialogContent className="record-detail import-dialog"><DialogTitle>{kind==='history'?'导入抽牌历史备份':'导入命例备份'}</DialogTitle><DialogDescription>{pendingImport?.name} · 导入前先核对文件内容。</DialogDescription>{pendingImport&&<><div className="import-summary"><div><strong>{pendingImport.preview.total}</strong><span>{kind==='history'?'文件内记录':'文件内命例'}</span></div><div><strong>{pendingImport.preview.newCount}</strong><span>将要导入</span></div><div><strong>{pendingImport.preview.duplicateCount}</strong><span>完全重复</span></div></div><p className="import-duplicate-note">文件里的 index 只表示备份中的排列顺序；写入当前浏览器时会重新分配本机编号。完全相同的记录会自动跳过。</p><button className="import-confirm" onClick={applyImport}>确认导入</button></>}</DialogContent></Dialog>
 <Dialog open={adding} onOpenChange={setAdding}><DialogContent className="record-detail"><DialogTitle>添加命例</DialogTitle><DialogDescription>保存原始出生日期、钟表时间和当时的设置。</DialogDescription><CaseEditor onSaved={()=>{setAdding(false);setRecords(listRecords('cases'));setNotice('命例已保存。')}}/></DialogContent></Dialog>
 <AlertDialog open={confirm!==null} onOpenChange={v=>{if(!v)setConfirm(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirm==='all'?'清空这些记录？':'删除这条记录？'}</AlertDialogTitle><AlertDialogDescription>{confirm==='all'?`将删除此列表中的 ${shown.length} 条记录。`:'将删除所选记录。'}此操作无法撤销。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>保留记录</AlertDialogCancel><AlertDialogAction onClick={remove}>确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={Boolean(detail)} onOpenChange={v=>{if(!v)setDetail(null)}}><DialogContent className="record-detail"><DialogTitle data-no-i18n>{detail?.title}</DialogTitle><DialogDescription>{detail&&`${detail.kind==='tarot'?'塔罗记录':'出生资料'} · ${formatDate(detail.createdAt)}`}</DialogDescription>{detail?.kind==='tarot'?<div className="detail-cards">{detail.snapshot.cards.map((c:TarotCard)=><figure key={c.id}><Image unoptimized loading="lazy" width={150} height={257} src={`/tools/tarot/assets/tarot/web/table/${CARD_FILES[c.id]}`} className={c.reversed?'reversed':''} alt={c.name}/><figcaption><span>{c.position}</span><b>{c.name}</b><small>{c.reversed?'逆位':'正位'}</small></figcaption></figure>)}</div>:detail&&<><p className="record-description">这份出生资料可用于不同排盘工具，各工具的计算结果保存在同一命例中。</p><button className="pill-link" onClick={()=>{setDetail(null);onOpen('bazi',detail.id)}}>排八字 <ArrowUpRight size={16}/></button><details><summary>查看保存时的完整结果</summary><pre>{JSON.stringify(detail.charts||detail.snapshot,null,2)}</pre></details></>}</DialogContent></Dialog>
 </section>;
}
