'use client';
/* oxlint-disable react/react-compiler next/no-img-element -- browser storage hydration and static vendored artwork are intentional here */
import {Component,lazy,Suspense,useEffect,useState,type ReactNode} from 'react';
import {ArrowUpRight,Grid2X2,BookOpen,History,Settings2,ArrowRight,Pin,Orbit,Info,type LucideIcon} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarTrigger,SidebarMenu,SidebarMenuItem,SidebarMenuButton,useSidebar} from '@/components/ui/sidebar';
import {Skeleton} from '@/components/ui/skeleton';
import {tools,nameOf,type ToolId} from './tool-catalog';
import {HOME_TITLE,SITE_NAME,TOOL_SEO} from './seo';
import LanguageSwitcher from './language-switcher';
import {registerPersonalTools} from '../public/shared/agent-tools.js';
import {getFeatured,getPreferences,recordUsage,listRecords} from '../public/shared/storage.js';
const PersonalPanel=lazy(()=>import('./personal-panel'));
const ToolFrame=lazy(()=>import('./tool-frame'));
const AboutPanel=lazy(()=>import('./about-panel'));
const DAILY_NOTES=[['有些答案，','慢一点才会出现。'],['看看时间，','也看看自己。'],['从一个问题开始，','慢慢找到方向。'],['给未知，','留一个位置。'],['今日所问，','也许已有方向。']] as const;
const isToolId=(value:string):value is ToolId=>tools.some(tool=>tool.id===value);
type ToolSessions=Partial<Record<ToolId,string|undefined>>;
const rememberSession=(current:ToolSessions,tool:ToolId,record?:string)=>Object.hasOwn(current,tool)&&current[tool]===record?current:{...current,[tool]:record};
const titleOf=(view:string)=>view==='home'?HOME_TITLE:view==='about'?`关于 OpenDestiny Web｜${SITE_NAME}`:view==='cases'?`命例簿｜${SITE_NAME}`:view==='history'?`抽牌历史｜${SITE_NAME}`:view in TOOL_SEO?`${TOOL_SEO[view as ToolId].title}｜${SITE_NAME}`:`${nameOf(view)}｜${SITE_NAME}`;
class LoadBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<div role="alert" className="panel-loading">暂时没能载入，请检查网络。<button onClick={()=>location.reload()}>重新加载</button></div>:this.props.children}}
export default function Workspace({initialView='home'}:{initialView?:string}){
 const [view,setView]=useState(initialView),[settings,setSettings]=useState(false),[featured,setFeatured]=useState<ToolId>('tarot'),[fixed,setFixed]=useState(false),[revision,setRevision]=useState(0),[error,setError]=useState(''),[counts,setCounts]=useState({cases:0,history:0}),[dailyNote,setDailyNote]=useState<(typeof DAILY_NOTES)[number]>(DAILY_NOTES[0]);
 const [toolSessions,setToolSessions]=useState<ToolSessions>(()=>isToolId(initialView)?{[initialView]:undefined}:{});
 useEffect(()=>{const refresh=()=>{try{setFeatured(getFeatured());const p=getPreferences();setFixed(p.featured!=='auto');document.documentElement.dataset.motion=p.motion?'on':'off';const r=listRecords();setCounts({cases:r.filter(x=>x.kind!=='tarot').length,history:r.filter(x=>x.kind==='tarot').length});setRevision(n=>n+1);setError('')}catch{setError('当前浏览器无法读取保存的数据。原有数据未被覆盖。')}};refresh();const message=(e:MessageEvent)=>{if(e.origin===location.origin&&e.data?.type==='tools-data')refresh()};window.addEventListener('tools-data',refresh);window.addEventListener('storage',refresh);window.addEventListener('message',message);return()=>{window.removeEventListener('tools-data',refresh);window.removeEventListener('storage',refresh);window.removeEventListener('message',message)}},[]);
 useEffect(()=>registerPersonalTools((document as Document & {modelContext?:unknown}).modelContext),[]);
 useEffect(()=>{const d=new Date();const day=Math.floor(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())/86400000);setDailyNote(DAILY_NOTES[day%DAILY_NOTES.length])},[]);
 const navigate=(next:string,recordId?:string)=>{const path=next==='home'?'/':`/${next}/`;window.history.pushState(null,'',path+(recordId?'?record='+encodeURIComponent(recordId):''));document.title=titleOf(next);if(isToolId(next))setToolSessions(current=>rememberSession(current,next,recordId));setView(next);setSettings(false)};
 useEffect(()=>{const sync=()=>{const segment=location.pathname.split('/').filter(Boolean)[0]||'home',next=['bazi','ziwei','tarot','calendar','qishuo','cases','history','about'].includes(segment)?segment:'home',recordId=new URLSearchParams(location.search).get('record')||undefined;document.title=titleOf(next);if(isToolId(next))setToolSessions(current=>rememberSession(current,next,recordId));setView(next);setSettings(false)};sync();window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync)},[]);
 const openTool=(id:ToolId,recordId?:string)=>{setSettings(false);try{recordUsage(id)}catch{setError('无法保存使用偏好，本次仍可使用工具。')}navigate(id,recordId)};
 const followTool=(event:React.MouseEvent<HTMLAnchorElement>,id:ToolId)=>{if(event.button||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();openTool(id)};
 const home=()=>navigate('home');
 const primary=tools.find(t=>t.id===featured)!;
 const toolView=isToolId(view);
 const nav=(id:string,label:string,Icon:LucideIcon,count?:number)=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} onClick={()=>{navigate(id)}}><Icon/><span>{label}</span>{count!==undefined&&<span className="nav-count">{count.toString().padStart(2,'0')}</span>}</SidebarMenuButton></SidebarMenuItem>;
 return <SidebarProvider style={{'--sidebar-width':'232px'} as React.CSSProperties}><CloseMobileNavigation view={view+String(settings)}/><Sidebar className="workspace-sidebar"><SidebarHeader><button className="brand" onClick={home}><img className="brand-mark" src="/opendestiny-icon.png" alt="" width="41" height="41"/><span className="brand-copy">OpenDestiny Web<small>METAPHYSICS TOOLS</small></span></button></SidebarHeader><SidebarContent><div className="nav-label">工作空间</div><SidebarMenu>{nav('home','全部工具',Grid2X2,5)}</SidebarMenu><div className="nav-label">探索</div><SidebarMenu>{tools.map(t=><SidebarMenuItem key={t.id}><SidebarMenuButton isActive={view===t.id} onClick={()=>openTool(t.id)}><t.icon/><span>{t.name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="nav-label">我的空间</div><SidebarMenu>{nav('cases','命例簿',BookOpen,counts.cases)}{nav('history','抽牌历史',History,counts.history)}</SidebarMenu></SidebarContent><SidebarFooter><LanguageSwitcher/><SidebarMenu><SidebarMenuItem><SidebarMenuButton onClick={()=>setSettings(true)}><Settings2/><span>偏好设置</span></SidebarMenuButton></SidebarMenuItem>{nav('about','关于',Info)}</SidebarMenu><a className="back-home" href="https://redsc1.com">redsc1.com <ArrowUpRight size={14}/></a></SidebarFooter></Sidebar>
 <div className="main-shell">{!['tarot','bazi','ziwei','calendar','qishuo'].includes(view)&&<header className="topbar"><div><SidebarTrigger/><span>工作空间</span><span className="breadcrumb">/</span><b>{view==='home'?'全部工具':view==='cases'?'命例簿':view==='history'?'抽牌历史':view==='about'?'关于 OpenDestiny Web':nameOf(view)}</b></div><span className="edition"><span/>记录仅保存在本机</span></header>}{error&&<p role="alert" className="error-text workspace-error">{error}</p>}
 {view==='home'?<main className="desk"><div className="page-heading"><div><p className="eyebrow">A LITTLE SPACE FOR DISCOVERY</p><h1>留一点时间，<span>探索。</span></h1><p className="intro">你的工具、灵感与记录，在这里慢慢展开。</p></div><span className="heading-note">{dailyNote[0]}<br/><span>{dailyNote[1]}</span></span></div><div className="section-heading"><h2>所有工具 <span>05</span></h2><button className="featured-setting" onClick={()=>setSettings(true)}>{fixed?<Pin size={13}/>:<History size={13}/>} {fixed?'已固定首页主工具':'近 30 天常用'} <Settings2 size={13}/></button></div>
 <section className="tool-grid" aria-label="所有工具"><a href={`/${primary.id}/`} className={`tarot-card featured-${primary.id}`} onClick={event=>followTool(event,primary.id)}><div className="tarot-copy"><span className="eyebrow">{primary.en}</span><h2>{primary.name}<span>{primary.line}</span></h2><p>{primary.description}</p><span className="pill-link">{primary.id==='tarot'?'坐下来，抽一张':'打开'+primary.name} <ArrowUpRight size={18}/></span></div>{primary.id==='tarot'?<div className="card-fan" aria-hidden="true">{['01-magician','18-moon','19-sun'].map((n,i)=><img key={n} src={`/tools/tarot/assets/tarot/web/table/${n}.webp`} alt="" width="240" height="410" className={`playing-card card-${i}`} decoding="async"/>)}</div>:<div className="featured-visual" aria-hidden="true"><ToolVisual id={primary.id}/></div>}<span className="tarot-foot">{primary.en}<span>✦</span>{fixed?'为你固定的位置':'跟随最近的探索'}</span></a>{tools.filter(t=>t.id!==featured).map(t=><a href={`/${t.id}/`} key={t.id} onClick={event=>followTool(event,t.id)} className={`tool-card tool-${t.id}`}><div className="tool-top"><span className="eyebrow">{t.en}</span><ArrowUpRight size={20}/></div><div className="tool-visual" aria-hidden="true"><ToolVisual id={t.id}/></div><div className="tool-bottom"><h3>{t.name}</h3><p>{t.line}</p></div></a>)}</section>
 <section className="personal-strip"><div><span className="small-icon"><BookOpen size={22}/></span><div><h3>每一次探索，都值得留下。</h3><p>{counts.cases||counts.history?`${counts.cases} 份命例 · ${counts.history} 次抽牌记录`:'你的第一份命例、第一段抽牌记录，从这里开始。'}</p></div></div><button onClick={()=>navigate('cases')}>我的空间 <ArrowRight size={17}/></button></section><footer className="desk-footer"><span>OpenDestiny Web</span><span>一点好奇，一方天地。</span></footer></main>:!toolView?<LoadBoundary key={view}><Suspense fallback={<output className="view-loading"><Skeleton className="h-7 w-40"/><p>正在打开工作空间…</p></output>}>{view==='about'?<AboutPanel/>:<PersonalPanel kind={view as 'cases'|'history'} onClose={home} onOpen={openTool} revision={revision}/>}</Suspense></LoadBoundary>:null}
 <div className="tool-session-stack" hidden={!toolView}>{tools.map(tool=>Object.hasOwn(toolSessions,tool.id)&&<div className="tool-session" hidden={view!==tool.id} key={tool.id}><LoadBoundary key={`${tool.id}-${toolSessions[tool.id]??''}`}><Suspense fallback={<output className="view-loading"><Skeleton className="h-7 w-40"/><p>正在打开工作空间…</p></output>}><ToolFrame tool={tool.id} record={toolSessions[tool.id]} onBack={home}/></Suspense></LoadBoundary></div>)}</div></div>
 {settings&&<LoadBoundary><Suspense fallback={<output className="panel-loading">正在打开偏好设置…</output>}><PersonalPanel kind="settings" onClose={()=>setSettings(false)} onOpen={openTool} revision={revision}/></Suspense></LoadBoundary>}</SidebarProvider>;
}
function ToolVisual({id}:{id:ToolId}){return id==='bazi'?<div className="pillars">{['甲','丙','戊','壬'].map((x,n)=><div key={x}><small>{['年','月','日','时'][n]}</small><b>{x}</b><b>{['辰','寅','午','子'][n]}</b></div>)}</div>:id==='ziwei'?<div className="ziwei-diagram">{['巳','午','未','申','辰','紫微','酉','卯','斗数','戌','寅','丑','子','亥'].map((x,n)=><span key={n}>{x}</span>)}</div>:id==='calendar'?<div className="calendar-art"><span>日 一 二 三 四 五 六</span><div>{Array.from({length:14},(_,n)=><b key={n} className={n===9?'selected':''}>{n+1}</b>)}</div></div>:id==='qishuo'?<div className="orbit-art"><Orbit size={94} strokeWidth={.7}/><span>朔 <span>望</span> 晦</span></div>:<div className="mini-tarot"><img src="/tools/tarot/assets/tarot/web/table/01-magician.webp" alt="" width="62" height="106" loading="lazy"/><img src="/tools/tarot/assets/tarot/web/table/18-moon.webp" alt="" width="62" height="106" loading="lazy"/></div>}

function CloseMobileNavigation({view}:{view:string}){const {setOpenMobile}=useSidebar();useEffect(()=>setOpenMobile(false),[view,setOpenMobile]);return null}
